# Generated by Django 6.0.1 on 2026-06-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='نامک (لینک)')),
                ('content', models.TextField(verbose_name='محتوای مقاله')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='تصویر مقاله')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پروژه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='تصویر پروژه')),
                ('technologies', models.CharField(help_text='مثال: Django, Vue, Tailwind', max_length=255, verbose_name='تکنولوژی\u200cهای استفاده شده')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='لینک گیت\u200cهاب')),
                ('live_link', models.URLField(blank=True, null=True, verbose_name='لینک پیش\u200cنمایش (Live)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
