# Generated by Django 6.0.1 on 2026-06-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_project_image_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='تصویر شاخص'),
        ),
    ]
