# Generated by Django 6.0.1 on 2026-06-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projectimage_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mockup_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/mockups/', verbose_name='تصویر کامل (Mockup)'),
        ),
    ]
