name: Deploy Nuxt Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout Code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install Dependencies
        run: npm install
        working-directory: ./netara_nuxt # اجرای دستور در پوشه ناکست

      - name: 🔨 Build Nuxt Project
        run: npm run generate
        working-directory: ./netara_nuxt # اجرای دستور در پوشه ناکست

      - name: 🚀 Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: netara_nuxt/.output/public/ # آدرس جدید پوشه خروجی
          server-dir: public_html/
